EMERGENCY_LAND:
  type: system
  action: emergency
DOWN:
  action: decrease_altitude
  delta: -0.1
  type: drone
GUN:
  Rotation_Independent: false
HALF_HEART:
  Rotation_Independent: false
LEFT:
  action: yaw_left
  delta: 0.1
  type: drone
MIDDLE:
  Rotation_Independent: true
OK:
  Rotation_Independent: false
  action: toggle_flight_mode
  type: system
PEACE:
  Rotation_Independent: false
  action: arm
  type: system
POINTER:
  Rotation_Independent: false
  type: test
RIGHT:
  action: yaw_right
  delta: 0.1
  type: drone
ROCK_AND_ROLL:
  Rotation_Independent: false
STOP:
  Rotation_Independent: true
THUMBS_DOWN:
  Rotation_Independent: true
  action: yaw_left
  delta: 0.1
  type: drone
THUMBS_NEUTRAL:
  Rotation_Independent: false
THUMBS_UP:
  Rotation_Independent: false
THUMB_UP:
  Rotation_Independent: false
  action: increase_altitude
  delta: 0.1
  type: drone
UP:
  Rotation_Independent: false
  action: increase_altitude
  delta: 0.2
  type: drone
